using AlecEdu_api.Domain.Entities;

namespace AlecEdu_api.Infrastructure.Persistence.Seeds;

public static class TinhSeed
{
    public static IEnumerable<Tinh> getTinhs()
    {
        return new List<Tinh>
        {
            new() { Id = 1, TenTinh = "Thành phố Hà Nội" },
            new() { Id = 2, TenTinh = "Tỉnh Hà Giang" },
            new() { Id = 3, TenTinh = "Tỉnh Cao Bằng" },
            new() { Id = 4, TenTinh = "Tỉnh Bắc Kạn" },
            new() { Id = 5, TenTinh = "Tỉnh Tuyên Quang" },
            new() { Id = 6, TenTinh = "Tỉnh Lào Cai" },
            new() { Id = 7, TenTinh = "Tỉnh Điện Biên" },
            new() { Id = 8, TenTinh = "Tỉnh Lai Châu" },
            new() { Id = 9, TenTinh = "Tỉnh Sơn La" },
            new() { Id = 10, TenTinh = "Tỉnh Yên Bái" },
            new() { Id = 11, TenTinh = "Tỉnh Hoà Bình" },
            new() { Id = 12, TenTinh = "Tỉnh Thái Nguyên" },
            new() { Id = 13, TenTinh = "Tỉnh Lạng Sơn" },
            new() { Id = 14, TenTinh = "Tỉnh Quảng Ninh" },
            new() { Id = 15, TenTinh = "Tỉnh Bắc Giang" },
            new() { Id = 16, TenTinh = "Tỉnh Phú Thọ" },
            new() { Id = 17, TenTinh = "Tỉnh Vĩnh Phúc" },
            new() { Id = 18, TenTinh = "Tỉnh Bắc Ninh" },
            new() { Id = 19, TenTinh = "Tỉnh Hải Dương" },
            new() { Id = 20, TenTinh = "Thành phố Hải Phòng" },
            new() { Id = 21, TenTinh = "Tỉnh Hưng Yên" },
            new() { Id = 22, TenTinh = "Tỉnh Thái Bình" },
            new() { Id = 23, TenTinh = "Tỉnh Hà Nam" },
            new() { Id = 24, TenTinh = "Tỉnh Nam Định" },
            new() { Id = 25, TenTinh = "Tỉnh Ninh Bình" },
            new() { Id = 26, TenTinh = "Tỉnh Thanh Hóa" },
            new() { Id = 27, TenTinh = "Tỉnh Nghệ An" },
            new() { Id = 28, TenTinh = "Tỉnh Hà Tĩnh" },
            new() { Id = 29, TenTinh = "Tỉnh Quảng Bình" },
            new() { Id = 30, TenTinh = "Tỉnh Quảng Trị" },
            new() { Id = 31, TenTinh = "Tỉnh Thừa Thiên Huế" },
            new() { Id = 32, TenTinh = "Thành phố Đà Nẵng" },
            new() { Id = 33, TenTinh = "Tỉnh Quảng Nam" },
            new() { Id = 34, TenTinh = "Tỉnh Quảng Ngãi" },
            new() { Id = 35, TenTinh = "Tỉnh Bình Định" },
            new() { Id = 36, TenTinh = "Tỉnh Phú Yên" },
            new() { Id = 37, TenTinh = "Tỉnh Khánh Hòa" },
            new() { Id = 38, TenTinh = "Tỉnh Ninh Thuận" },
            new() { Id = 39, TenTinh = "Tỉnh Bình Thuận" },
            new() { Id = 40, TenTinh = "Tỉnh Kon Tum" },
            new() { Id = 41, TenTinh = "Tỉnh Gia Lai" },
            new() { Id = 42, TenTinh = "Tỉnh Đắk Lắk" },
            new() { Id = 43, TenTinh = "Tỉnh Đắk Nông" },
            new() { Id = 44, TenTinh = "Tỉnh Lâm Đồng" },
            new() { Id = 45, TenTinh = "Tỉnh Bình Phước" },
            new() { Id = 46, TenTinh = "Tỉnh Tây Ninh" },
            new() { Id = 47, TenTinh = "Tỉnh Bình Dương" },
            new() { Id = 48, TenTinh = "Tỉnh Đồng Nai" },
            new() { Id = 49, TenTinh = "Tỉnh Bà Rịa - Vũng Tàu" },
            new() { Id = 50, TenTinh = "Thành phố Hồ Chí Minh" },
            new() { Id = 51, TenTinh = "Tỉnh Long An" },
            new() { Id = 52, TenTinh = "Tỉnh Tiền Giang" },
            new() { Id = 53, TenTinh = "Tỉnh Bến Tre" },
            new() { Id = 54, TenTinh = "Tỉnh Trà Vinh" },
            new() { Id = 55, TenTinh = "Tỉnh Vĩnh Long" },
            new() { Id = 56, TenTinh = "Tỉnh Đồng Tháp" },
            new() { Id = 57, TenTinh = "Tỉnh An Giang" },
            new() { Id = 58, TenTinh = "Tỉnh Kiên Giang" },
            new() { Id = 59, TenTinh = "Thành phố Cần Thơ" },
            new() { Id = 60, TenTinh = "Tỉnh Hậu Giang" },
            new() { Id = 61, TenTinh = "Tỉnh Sóc Trăng" },
            new() { Id = 62, TenTinh = "Tỉnh Bạc Liêu" },
            new() { Id = 63, TenTinh = "Tỉnh Cà Mau" },
        };
    }
}
