abstract class FormValidator {
  String name();
  String required();
  String minLength(String v, int n);
  String maxLength(String v, int n);
  String email(String v);
  String phoneNumber(String v);
  String ip(String v);
  String ipv6(String v);
  String url(String v);
  String fqdn(String v);
  String alpha(String v);
  String numeric(String v);
  String alphanumeric(String v);
  String base64(String v);
  String isInt(String v);
  String isFloat(String v);
  String hexadecimal(String v);
  String hexColor(String v);
  String lowercase(String v);
  String uppercase(String v);
  String divisibleBy(String v, int n);
  String isNull(String v);
  String length(String v, int n);
  String byteLength(String v, int n);
  String uuid(String v);
  String date(String v);
  String after(String v, [DateTime? date]);
  String before(String v, [DateTime? date]);
  String creditCard(String v);
  String isbn(String v);
  String json(String v);
  String multibyte(String v);
  String ascii(String v);
  String fullWidth(String v);
  String halfWidth(String v);
  String variableWidth(String v);
  String surrogatePair(String v);
  String mongoId(String v);
  String postalCode(String v);
}
