version: '3.8'

volumes:
  microsoft_account_data:
    name: microsoft_account_data
    
services:
  microsoft_accounts:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: microsoft_account_db
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - microsoft_account_data:/var/lib/sqlserver/data
    ports:
      - "1435:1433"